### ISSUE TITLE
previous/next navigation with keyboard keys?

### ISSUE THREAD

**Issue by ffd8** [antiboredom/piplayer#1]
This looks awesome and maybe perfect for an upcoming installation... have you considered adding settings for assigning two keyboard keys for previos/next video jumping? Ie, one may have a vidplayer running on RPi and attach arcade buttons to GPIO as HiD device or a macro keyboard (these lil things with 2+ keys). Would love to have a 2 key keyboard below a screen that simply goes prev/next to a playlist.

![2-key-macro](https://github.com/antiboredom/piplayer/assets/570957/3e0408ca-f24d-4e80-9ad0-4497081e05ab)

**Comment by ffd8** [comment]
Hmm silly issue – of course VLC has hotkeys for prev/next that can hopefully also be used in the RPi version – just have to customize the macro-keyboard to hit them... solved

**Comment by antiboredom** [comment]
Glad to hear this could be useful for you! Let me know if you run into any other issues...
